version: '3.8'

services:
  postgres-db:
    image: postgres:15.3
    container_name: db-wallet-app
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    container_name: redis-server-wallet
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
