# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build backend-wallet`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t backend-wallet`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system backend-wallet && \
          adduser --system -G backend-wallet backend-wallet

COPY dist/backend-wallet backend-wallet/
RUN chown -R backend-wallet:backend-wallet .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix backend-wallet --omit=dev -f install

CMD [ "node", "backend-wallet" ]
