openapi: 3.1.0
info:
  title: API de Usuarios
  version: 1.0.0
  description: Documentación de API para la gestión de usuarios
servers:
  - url: http://localhost:3000/api
    description: Servidor de desarrollo

paths:
  /users:
    $ref: './paths/user.yml'    

components:
  schemas:
    $ref: './components/schemas.yml'
  responses:
    ServerError:
      $ref: './components/responses.yml'
    
    
